# Generated by Django 6.0 on 2025-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('registration', 'Регистрация'), ('view_product', 'Просмотр товара'), ('add_to_favorites', 'Добавление в избранное'), ('remove_from_favorites', 'Удаление из избранного'), ('update_profile', 'Обновление профиля'), ('add_to_cart', 'Добавление в корзину'), ('purchase', 'Покупка'), ('review', 'Оставление отзыва')], max_length=50, verbose_name='Тип активности'),
        ),
    ]
