# Generated by Django 6.0 on 2025-12-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кухня', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(upload_to='kitchens/', verbose_name='Основное изображение'),
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchens/gallery/', verbose_name='Дополнительное фото')),
                ('alt_text', models.CharField(blank=True, help_text="Необязательно, например: 'Вид сбоку', 'Интерьер'", max_length=200, verbose_name='Описание фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше показывается', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.kitchen', verbose_name='Кухня')),
            ],
            options={
                'verbose_name': 'Фотография кухни',
                'verbose_name_plural': 'Фотографии кухни',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
